### ISSUE TITLE
binding.d which cannot be read

### ISSUE THREAD

**Issue by o3o** [symmetryinvestments/jsonneD#3]
Same code as #1,

```
../../../.dub/packages/jsonned-1.0.1/jsonned/source/jsonned/package.d(3,8): Error: module `binding` is in file 'binding.d' which cannot be read
```

Can you check my [repo](https://github.com/o3o/jsonneD)?

Thank you!

**Comment by burner** [comment]
again thanks, v1.0.2 should be good now

**Comment by burner** [comment]
I spoke to soon, made a typo

**Comment by burner** [comment]
v1.0.3 sorry for the trouble

**Comment by o3o** [comment]
You're welcome!
Now it works like a charm

Thank you

**Comment by burner** [comment]
+1
